// <auto-generated />
using System;
using GameRequirements.Domain.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GameRequirements.Api.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20250925203013_Add_Processors_Seed")]
    partial class Add_Processors_Seed
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("GameRequirements.Domain.Entites.Completing_computers.DBComputer", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("ProcessorId")
                        .HasColumnType("bigint");

                    b.Property<int>("RAM")
                        .HasColumnType("int");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.Property<Guid>("Uuid")
                        .HasColumnType("uniqueidentifier");

                    b.Property<long>("VideoCardId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("ProcessorId");

                    b.HasIndex("UserId");

                    b.HasIndex("VideoCardId");

                    b.ToTable("Computers");
                });

            modelBuilder.Entity("GameRequirements.Domain.Entites.Completing_computers.DBProcessor", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<double>("BaseFrequencyGHz")
                        .HasColumnType("float");

                    b.Property<double>("BoostFrequencyGHz")
                        .HasColumnType("float");

                    b.Property<int>("Cores")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("Threads")
                        .HasColumnType("int");

                    b.Property<Guid>("Uuid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWID()");

                    b.HasKey("Id");

                    b.ToTable("Processors", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            BaseFrequencyGHz = 3.6000000000000001,
                            BoostFrequencyGHz = 4.2999999999999998,
                            Cores = 4,
                            Name = "Intel Core i3-10100",
                            Threads = 8,
                            Uuid = new Guid("ea7a7139-5ca2-4b74-87a2-41198dfb338a")
                        },
                        new
                        {
                            Id = 2L,
                            BaseFrequencyGHz = 3.6000000000000001,
                            BoostFrequencyGHz = 4.2999999999999998,
                            Cores = 4,
                            Name = "Intel Core i3-10100F",
                            Threads = 8,
                            Uuid = new Guid("273ab482-080e-4062-a5f7-7ebfd3f45a5e")
                        },
                        new
                        {
                            Id = 3L,
                            BaseFrequencyGHz = 2.8999999999999999,
                            BoostFrequencyGHz = 4.2999999999999998,
                            Cores = 6,
                            Name = "Intel Core i5-10400F",
                            Threads = 12,
                            Uuid = new Guid("6f642142-4354-4a79-8a8e-9383d81726ff")
                        },
                        new
                        {
                            Id = 4L,
                            BaseFrequencyGHz = 2.6000000000000001,
                            BoostFrequencyGHz = 4.4000000000000004,
                            Cores = 6,
                            Name = "Intel Core i5-11400F",
                            Threads = 12,
                            Uuid = new Guid("5c63858d-8e62-4516-835d-4189895185e3")
                        },
                        new
                        {
                            Id = 5L,
                            BaseFrequencyGHz = 2.5,
                            BoostFrequencyGHz = 4.4000000000000004,
                            Cores = 6,
                            Name = "Intel Core i5-12400F",
                            Threads = 12,
                            Uuid = new Guid("8a7ea12b-f767-4b99-bf02-acc625fa7a4f")
                        },
                        new
                        {
                            Id = 6L,
                            BaseFrequencyGHz = 2.5,
                            BoostFrequencyGHz = 4.5999999999999996,
                            Cores = 10,
                            Name = "Intel Core i5-13400F",
                            Threads = 16,
                            Uuid = new Guid("f5569059-104a-4ea1-80db-cce9df74c7a9")
                        },
                        new
                        {
                            Id = 7L,
                            BaseFrequencyGHz = 3.7000000000000002,
                            BoostFrequencyGHz = 4.7000000000000002,
                            Cores = 6,
                            Name = "Intel Core i7-8700K",
                            Threads = 12,
                            Uuid = new Guid("b4f431d6-3c87-487b-9a26-bbb6ecdee9bc")
                        },
                        new
                        {
                            Id = 8L,
                            BaseFrequencyGHz = 3.7999999999999998,
                            BoostFrequencyGHz = 5.0999999999999996,
                            Cores = 8,
                            Name = "Intel Core i7-10700K",
                            Threads = 16,
                            Uuid = new Guid("6b0edbe9-92c7-4a5f-90ff-a85ead1d26fd")
                        },
                        new
                        {
                            Id = 9L,
                            BaseFrequencyGHz = 3.6000000000000001,
                            BoostFrequencyGHz = 5.0,
                            Cores = 8,
                            Name = "Intel Core i9-9900K",
                            Threads = 16,
                            Uuid = new Guid("a0d839ee-9e47-4c6e-b381-03c021d15fba")
                        },
                        new
                        {
                            Id = 10L,
                            BaseFrequencyGHz = 3.2000000000000002,
                            BoostFrequencyGHz = 5.2000000000000002,
                            Cores = 16,
                            Name = "Intel Core i9-12900K",
                            Threads = 24,
                            Uuid = new Guid("e794ae77-890c-4fe8-ba07-c8e525fb0790")
                        },
                        new
                        {
                            Id = 101L,
                            BaseFrequencyGHz = 3.6000000000000001,
                            BoostFrequencyGHz = 4.2000000000000002,
                            Cores = 6,
                            Name = "AMD Ryzen 5 3600",
                            Threads = 12,
                            Uuid = new Guid("299d8c53-bcc2-4fb5-8b87-df4a47390a74")
                        },
                        new
                        {
                            Id = 102L,
                            BaseFrequencyGHz = 3.6000000000000001,
                            BoostFrequencyGHz = 4.4000000000000004,
                            Cores = 8,
                            Name = "AMD Ryzen 7 3700X",
                            Threads = 16,
                            Uuid = new Guid("4256ff61-0d44-43c9-95bc-0b148542d3dd")
                        },
                        new
                        {
                            Id = 103L,
                            BaseFrequencyGHz = 3.5,
                            BoostFrequencyGHz = 4.4000000000000004,
                            Cores = 6,
                            Name = "AMD Ryzen 5 5600",
                            Threads = 12,
                            Uuid = new Guid("e13f45dc-9e17-4b95-a654-2d398f2009b6")
                        },
                        new
                        {
                            Id = 104L,
                            BaseFrequencyGHz = 3.7000000000000002,
                            BoostFrequencyGHz = 4.5999999999999996,
                            Cores = 6,
                            Name = "AMD Ryzen 5 5600X",
                            Threads = 12,
                            Uuid = new Guid("2744b009-b20c-4675-8f46-31161942512c")
                        },
                        new
                        {
                            Id = 105L,
                            BaseFrequencyGHz = 3.7999999999999998,
                            BoostFrequencyGHz = 4.7000000000000002,
                            Cores = 8,
                            Name = "AMD Ryzen 7 5800X",
                            Threads = 16,
                            Uuid = new Guid("7d47e51c-00b2-4185-9863-761b645d95b2")
                        });
                });

            modelBuilder.Entity("GameRequirements.Domain.Entites.Completing_computers.DBVideoCard", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<double>("Boost_Clock_MHz")
                        .HasColumnType("float");

                    b.Property<int>("Bus_Width")
                        .HasColumnType("int");

                    b.Property<int>("Cuda_Or_Stream_Cores")
                        .HasColumnType("int");

                    b.Property<int>("Memory_Bandwidth_GB")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("RT_Units")
                        .HasColumnType("int");

                    b.Property<int>("Tensor_Units")
                        .HasColumnType("int");

                    b.Property<Guid>("Uuid")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("VRAM_GB")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("VideoCards");
                });

            modelBuilder.Entity("GameRequirements.Domain.Entites.Games.DBGames", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("MinCpuModel")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<string>("MinGpuModel")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<int>("MinRamGB")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("RecCpuModel")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<string>("RecGpuModel")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<int>("RecRamGB")
                        .HasColumnType("int");

                    b.Property<Guid>("Uuid")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.ToTable("Games");
                });

            modelBuilder.Entity("GameRequirements.Domain.Entites.User.DBUser", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<DateTime>("LoginDateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<Guid>("Uuid")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("GameRequirements.Domain.Entites.User.DBUserSession", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("JwtId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("Redeemed")
                        .HasColumnType("bit");

                    b.Property<string>("RefreshToken")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("RefreshTokenExpiration")
                        .HasColumnType("datetime2");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.Property<Guid>("Uuid")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Sessions");
                });

            modelBuilder.Entity("GameRequirements.Domain.Entites.Completing_computers.DBComputer", b =>
                {
                    b.HasOne("GameRequirements.Domain.Entites.Completing_computers.DBProcessor", "Processor")
                        .WithMany()
                        .HasForeignKey("ProcessorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GameRequirements.Domain.Entites.User.DBUser", "User")
                        .WithMany("Computers")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GameRequirements.Domain.Entites.Completing_computers.DBVideoCard", "VideoCard")
                        .WithMany()
                        .HasForeignKey("VideoCardId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Processor");

                    b.Navigation("User");

                    b.Navigation("VideoCard");
                });

            modelBuilder.Entity("GameRequirements.Domain.Entites.User.DBUserSession", b =>
                {
                    b.HasOne("GameRequirements.Domain.Entites.User.DBUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("GameRequirements.Domain.Entites.User.DBUser", b =>
                {
                    b.Navigation("Computers");
                });
#pragma warning restore 612, 618
        }
    }
}
