// <auto-generated />
using System;
using GameRequirements.Domain.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GameRequirements.Api.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20250925205016_Add_Games_Seed")]
    partial class Add_Games_Seed
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("GameRequirements.Domain.Entites.Completing_computers.DBComputer", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("ProcessorId")
                        .HasColumnType("bigint");

                    b.Property<int>("RAM")
                        .HasColumnType("int");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.Property<Guid>("Uuid")
                        .HasColumnType("uniqueidentifier");

                    b.Property<long>("VideoCardId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("ProcessorId");

                    b.HasIndex("UserId");

                    b.HasIndex("VideoCardId");

                    b.ToTable("Computers");
                });

            modelBuilder.Entity("GameRequirements.Domain.Entites.Completing_computers.DBProcessor", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<double>("BaseFrequencyGHz")
                        .HasColumnType("float");

                    b.Property<double>("BoostFrequencyGHz")
                        .HasColumnType("float");

                    b.Property<int>("Cores")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("Threads")
                        .HasColumnType("int");

                    b.Property<Guid>("Uuid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWID()");

                    b.HasKey("Id");

                    b.ToTable("Processors", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            BaseFrequencyGHz = 3.6000000000000001,
                            BoostFrequencyGHz = 4.2999999999999998,
                            Cores = 4,
                            Name = "Intel Core i3-10100",
                            Threads = 8,
                            Uuid = new Guid("ea7a7139-5ca2-4b74-87a2-41198dfb338a")
                        },
                        new
                        {
                            Id = 2L,
                            BaseFrequencyGHz = 3.6000000000000001,
                            BoostFrequencyGHz = 4.2999999999999998,
                            Cores = 4,
                            Name = "Intel Core i3-10100F",
                            Threads = 8,
                            Uuid = new Guid("273ab482-080e-4062-a5f7-7ebfd3f45a5e")
                        },
                        new
                        {
                            Id = 3L,
                            BaseFrequencyGHz = 2.8999999999999999,
                            BoostFrequencyGHz = 4.2999999999999998,
                            Cores = 6,
                            Name = "Intel Core i5-10400F",
                            Threads = 12,
                            Uuid = new Guid("6f642142-4354-4a79-8a8e-9383d81726ff")
                        },
                        new
                        {
                            Id = 4L,
                            BaseFrequencyGHz = 2.6000000000000001,
                            BoostFrequencyGHz = 4.4000000000000004,
                            Cores = 6,
                            Name = "Intel Core i5-11400F",
                            Threads = 12,
                            Uuid = new Guid("5c63858d-8e62-4516-835d-4189895185e3")
                        },
                        new
                        {
                            Id = 5L,
                            BaseFrequencyGHz = 2.5,
                            BoostFrequencyGHz = 4.4000000000000004,
                            Cores = 6,
                            Name = "Intel Core i5-12400F",
                            Threads = 12,
                            Uuid = new Guid("8a7ea12b-f767-4b99-bf02-acc625fa7a4f")
                        },
                        new
                        {
                            Id = 6L,
                            BaseFrequencyGHz = 2.5,
                            BoostFrequencyGHz = 4.5999999999999996,
                            Cores = 10,
                            Name = "Intel Core i5-13400F",
                            Threads = 16,
                            Uuid = new Guid("f5569059-104a-4ea1-80db-cce9df74c7a9")
                        },
                        new
                        {
                            Id = 7L,
                            BaseFrequencyGHz = 3.7000000000000002,
                            BoostFrequencyGHz = 4.7000000000000002,
                            Cores = 6,
                            Name = "Intel Core i7-8700K",
                            Threads = 12,
                            Uuid = new Guid("b4f431d6-3c87-487b-9a26-bbb6ecdee9bc")
                        },
                        new
                        {
                            Id = 8L,
                            BaseFrequencyGHz = 3.7999999999999998,
                            BoostFrequencyGHz = 5.0999999999999996,
                            Cores = 8,
                            Name = "Intel Core i7-10700K",
                            Threads = 16,
                            Uuid = new Guid("6b0edbe9-92c7-4a5f-90ff-a85ead1d26fd")
                        },
                        new
                        {
                            Id = 9L,
                            BaseFrequencyGHz = 3.6000000000000001,
                            BoostFrequencyGHz = 5.0,
                            Cores = 8,
                            Name = "Intel Core i9-9900K",
                            Threads = 16,
                            Uuid = new Guid("a0d839ee-9e47-4c6e-b381-03c021d15fba")
                        },
                        new
                        {
                            Id = 10L,
                            BaseFrequencyGHz = 3.2000000000000002,
                            BoostFrequencyGHz = 5.2000000000000002,
                            Cores = 16,
                            Name = "Intel Core i9-12900K",
                            Threads = 24,
                            Uuid = new Guid("e794ae77-890c-4fe8-ba07-c8e525fb0790")
                        },
                        new
                        {
                            Id = 101L,
                            BaseFrequencyGHz = 3.6000000000000001,
                            BoostFrequencyGHz = 4.2000000000000002,
                            Cores = 6,
                            Name = "AMD Ryzen 5 3600",
                            Threads = 12,
                            Uuid = new Guid("299d8c53-bcc2-4fb5-8b87-df4a47390a74")
                        },
                        new
                        {
                            Id = 102L,
                            BaseFrequencyGHz = 3.6000000000000001,
                            BoostFrequencyGHz = 4.4000000000000004,
                            Cores = 8,
                            Name = "AMD Ryzen 7 3700X",
                            Threads = 16,
                            Uuid = new Guid("4256ff61-0d44-43c9-95bc-0b148542d3dd")
                        },
                        new
                        {
                            Id = 103L,
                            BaseFrequencyGHz = 3.5,
                            BoostFrequencyGHz = 4.4000000000000004,
                            Cores = 6,
                            Name = "AMD Ryzen 5 5600",
                            Threads = 12,
                            Uuid = new Guid("e13f45dc-9e17-4b95-a654-2d398f2009b6")
                        },
                        new
                        {
                            Id = 104L,
                            BaseFrequencyGHz = 3.7000000000000002,
                            BoostFrequencyGHz = 4.5999999999999996,
                            Cores = 6,
                            Name = "AMD Ryzen 5 5600X",
                            Threads = 12,
                            Uuid = new Guid("2744b009-b20c-4675-8f46-31161942512c")
                        },
                        new
                        {
                            Id = 105L,
                            BaseFrequencyGHz = 3.7999999999999998,
                            BoostFrequencyGHz = 4.7000000000000002,
                            Cores = 8,
                            Name = "AMD Ryzen 7 5800X",
                            Threads = 16,
                            Uuid = new Guid("7d47e51c-00b2-4185-9863-761b645d95b2")
                        });
                });

            modelBuilder.Entity("GameRequirements.Domain.Entites.Completing_computers.DBVideoCard", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<double>("Boost_Clock_MHz")
                        .HasColumnType("float");

                    b.Property<int>("Bus_Width")
                        .HasColumnType("int");

                    b.Property<int>("Cuda_Or_Stream_Cores")
                        .HasColumnType("int");

                    b.Property<int>("Memory_Bandwidth_GB")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("RT_Units")
                        .HasColumnType("int");

                    b.Property<int>("Tensor_Units")
                        .HasColumnType("int");

                    b.Property<Guid>("Uuid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWID()");

                    b.Property<int>("VRAM_GB")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("VideoCards", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1001L,
                            Boost_Clock_MHz = 1680.0,
                            Bus_Width = 192,
                            Cuda_Or_Stream_Cores = 1920,
                            Memory_Bandwidth_GB = 336,
                            Name = "GeForce RTX 2060 6GB",
                            RT_Units = 30,
                            Tensor_Units = 240,
                            Uuid = new Guid("11111111-1111-1111-1111-111111111001"),
                            VRAM_GB = 6
                        },
                        new
                        {
                            Id = 1002L,
                            Boost_Clock_MHz = 1777.0,
                            Bus_Width = 192,
                            Cuda_Or_Stream_Cores = 3584,
                            Memory_Bandwidth_GB = 360,
                            Name = "GeForce RTX 3060 12GB",
                            RT_Units = 28,
                            Tensor_Units = 112,
                            Uuid = new Guid("11111111-1111-1111-1111-111111111002"),
                            VRAM_GB = 12
                        },
                        new
                        {
                            Id = 1003L,
                            Boost_Clock_MHz = 1665.0,
                            Bus_Width = 256,
                            Cuda_Or_Stream_Cores = 4864,
                            Memory_Bandwidth_GB = 448,
                            Name = "GeForce RTX 3060 Ti",
                            RT_Units = 38,
                            Tensor_Units = 152,
                            Uuid = new Guid("11111111-1111-1111-1111-111111111003"),
                            VRAM_GB = 8
                        },
                        new
                        {
                            Id = 1004L,
                            Boost_Clock_MHz = 1725.0,
                            Bus_Width = 256,
                            Cuda_Or_Stream_Cores = 5888,
                            Memory_Bandwidth_GB = 448,
                            Name = "GeForce RTX 3070",
                            RT_Units = 46,
                            Tensor_Units = 184,
                            Uuid = new Guid("11111111-1111-1111-1111-111111111004"),
                            VRAM_GB = 8
                        },
                        new
                        {
                            Id = 1005L,
                            Boost_Clock_MHz = 1710.0,
                            Bus_Width = 320,
                            Cuda_Or_Stream_Cores = 8704,
                            Memory_Bandwidth_GB = 760,
                            Name = "GeForce RTX 3080 10GB",
                            RT_Units = 68,
                            Tensor_Units = 272,
                            Uuid = new Guid("11111111-1111-1111-1111-111111111005"),
                            VRAM_GB = 10
                        },
                        new
                        {
                            Id = 1006L,
                            Boost_Clock_MHz = 1695.0,
                            Bus_Width = 384,
                            Cuda_Or_Stream_Cores = 10496,
                            Memory_Bandwidth_GB = 936,
                            Name = "GeForce RTX 3090",
                            RT_Units = 82,
                            Tensor_Units = 328,
                            Uuid = new Guid("11111111-1111-1111-1111-111111111006"),
                            VRAM_GB = 24
                        },
                        new
                        {
                            Id = 1007L,
                            Boost_Clock_MHz = 2460.0,
                            Bus_Width = 128,
                            Cuda_Or_Stream_Cores = 3072,
                            Memory_Bandwidth_GB = 272,
                            Name = "GeForce RTX 4060",
                            RT_Units = 24,
                            Tensor_Units = 96,
                            Uuid = new Guid("11111111-1111-1111-1111-111111111007"),
                            VRAM_GB = 8
                        },
                        new
                        {
                            Id = 1008L,
                            Boost_Clock_MHz = 2475.0,
                            Bus_Width = 192,
                            Cuda_Or_Stream_Cores = 5888,
                            Memory_Bandwidth_GB = 504,
                            Name = "GeForce RTX 4070",
                            RT_Units = 46,
                            Tensor_Units = 184,
                            Uuid = new Guid("11111111-1111-1111-1111-111111111008"),
                            VRAM_GB = 12
                        },
                        new
                        {
                            Id = 1009L,
                            Boost_Clock_MHz = 2610.0,
                            Bus_Width = 192,
                            Cuda_Or_Stream_Cores = 7680,
                            Memory_Bandwidth_GB = 504,
                            Name = "GeForce RTX 4070 Ti",
                            RT_Units = 60,
                            Tensor_Units = 240,
                            Uuid = new Guid("11111111-1111-1111-1111-111111111009"),
                            VRAM_GB = 12
                        },
                        new
                        {
                            Id = 1010L,
                            Boost_Clock_MHz = 2505.0,
                            Bus_Width = 256,
                            Cuda_Or_Stream_Cores = 9728,
                            Memory_Bandwidth_GB = 717,
                            Name = "GeForce RTX 4080",
                            RT_Units = 76,
                            Tensor_Units = 304,
                            Uuid = new Guid("11111111-1111-1111-1111-111111111010"),
                            VRAM_GB = 16
                        },
                        new
                        {
                            Id = 1011L,
                            Boost_Clock_MHz = 2520.0,
                            Bus_Width = 384,
                            Cuda_Or_Stream_Cores = 16384,
                            Memory_Bandwidth_GB = 1008,
                            Name = "GeForce RTX 4090",
                            RT_Units = 128,
                            Tensor_Units = 512,
                            Uuid = new Guid("11111111-1111-1111-1111-111111111011"),
                            VRAM_GB = 24
                        },
                        new
                        {
                            Id = 1101L,
                            Boost_Clock_MHz = 2491.0,
                            Bus_Width = 128,
                            Cuda_Or_Stream_Cores = 1792,
                            Memory_Bandwidth_GB = 224,
                            Name = "Radeon RX 6600",
                            RT_Units = 28,
                            Tensor_Units = 0,
                            Uuid = new Guid("22222222-2222-2222-2222-222222222001"),
                            VRAM_GB = 8
                        },
                        new
                        {
                            Id = 1102L,
                            Boost_Clock_MHz = 2589.0,
                            Bus_Width = 128,
                            Cuda_Or_Stream_Cores = 2048,
                            Memory_Bandwidth_GB = 256,
                            Name = "Radeon RX 6600 XT",
                            RT_Units = 32,
                            Tensor_Units = 0,
                            Uuid = new Guid("22222222-2222-2222-2222-222222222002"),
                            VRAM_GB = 8
                        },
                        new
                        {
                            Id = 1103L,
                            Boost_Clock_MHz = 2581.0,
                            Bus_Width = 192,
                            Cuda_Or_Stream_Cores = 2560,
                            Memory_Bandwidth_GB = 384,
                            Name = "Radeon RX 6700 XT",
                            RT_Units = 40,
                            Tensor_Units = 0,
                            Uuid = new Guid("22222222-2222-2222-2222-222222222003"),
                            VRAM_GB = 12
                        },
                        new
                        {
                            Id = 1104L,
                            Boost_Clock_MHz = 2105.0,
                            Bus_Width = 256,
                            Cuda_Or_Stream_Cores = 3840,
                            Memory_Bandwidth_GB = 512,
                            Name = "Radeon RX 6800",
                            RT_Units = 60,
                            Tensor_Units = 0,
                            Uuid = new Guid("22222222-2222-2222-2222-222222222004"),
                            VRAM_GB = 16
                        },
                        new
                        {
                            Id = 1105L,
                            Boost_Clock_MHz = 2250.0,
                            Bus_Width = 256,
                            Cuda_Or_Stream_Cores = 4608,
                            Memory_Bandwidth_GB = 512,
                            Name = "Radeon RX 6800 XT",
                            RT_Units = 72,
                            Tensor_Units = 0,
                            Uuid = new Guid("22222222-2222-2222-2222-222222222005"),
                            VRAM_GB = 16
                        },
                        new
                        {
                            Id = 1106L,
                            Boost_Clock_MHz = 2250.0,
                            Bus_Width = 256,
                            Cuda_Or_Stream_Cores = 5120,
                            Memory_Bandwidth_GB = 512,
                            Name = "Radeon RX 6900 XT",
                            RT_Units = 80,
                            Tensor_Units = 0,
                            Uuid = new Guid("22222222-2222-2222-2222-222222222006"),
                            VRAM_GB = 16
                        },
                        new
                        {
                            Id = 1107L,
                            Boost_Clock_MHz = 2655.0,
                            Bus_Width = 128,
                            Cuda_Or_Stream_Cores = 2048,
                            Memory_Bandwidth_GB = 288,
                            Name = "Radeon RX 7600",
                            RT_Units = 32,
                            Tensor_Units = 0,
                            Uuid = new Guid("22222222-2222-2222-2222-222222222007"),
                            VRAM_GB = 8
                        },
                        new
                        {
                            Id = 1108L,
                            Boost_Clock_MHz = 2544.0,
                            Bus_Width = 192,
                            Cuda_Or_Stream_Cores = 3456,
                            Memory_Bandwidth_GB = 432,
                            Name = "Radeon RX 7700 XT",
                            RT_Units = 54,
                            Tensor_Units = 0,
                            Uuid = new Guid("22222222-2222-2222-2222-222222222008"),
                            VRAM_GB = 12
                        },
                        new
                        {
                            Id = 1109L,
                            Boost_Clock_MHz = 2430.0,
                            Bus_Width = 256,
                            Cuda_Or_Stream_Cores = 3840,
                            Memory_Bandwidth_GB = 624,
                            Name = "Radeon RX 7800 XT",
                            RT_Units = 60,
                            Tensor_Units = 0,
                            Uuid = new Guid("22222222-2222-2222-2222-222222222009"),
                            VRAM_GB = 16
                        },
                        new
                        {
                            Id = 1110L,
                            Boost_Clock_MHz = 2400.0,
                            Bus_Width = 320,
                            Cuda_Or_Stream_Cores = 5376,
                            Memory_Bandwidth_GB = 800,
                            Name = "Radeon RX 7900 XT",
                            RT_Units = 84,
                            Tensor_Units = 0,
                            Uuid = new Guid("22222222-2222-2222-2222-222222222010"),
                            VRAM_GB = 20
                        },
                        new
                        {
                            Id = 1111L,
                            Boost_Clock_MHz = 2500.0,
                            Bus_Width = 384,
                            Cuda_Or_Stream_Cores = 6144,
                            Memory_Bandwidth_GB = 960,
                            Name = "Radeon RX 7900 XTX",
                            RT_Units = 96,
                            Tensor_Units = 0,
                            Uuid = new Guid("22222222-2222-2222-2222-222222222011"),
                            VRAM_GB = 24
                        });
                });

            modelBuilder.Entity("GameRequirements.Domain.Entites.Games.DBGames", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("MinCpuModel")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<string>("MinGpuModel")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<int>("MinRamGB")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("RecCpuModel")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<string>("RecGpuModel")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<int>("RecRamGB")
                        .HasColumnType("int");

                    b.Property<Guid>("Uuid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWID()");

                    b.HasKey("Id");

                    b.ToTable("Games", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 3001L,
                            Description = "RPG от CDPR в Найт-Сити. Данные соответствуют обновлённым требованиям Update 2.0/Phantom Liberty.",
                            MinCpuModel = "Core i7-6700 / Ryzen 5 1600",
                            MinGpuModel = "GTX 1060 6GB / RX 580 8GB",
                            MinRamGB = 12,
                            Name = "Cyberpunk 2077",
                            RecCpuModel = "Core i7-4790 / Ryzen 3 3200G",
                            RecGpuModel = "GTX 1660 Super / RX 590",
                            RecRamGB = 12,
                            Uuid = new Guid("33333333-3333-3333-3333-333333333001")
                        },
                        new
                        {
                            Id = 3002L,
                            Description = "Тактический шутер на Source 2. Valve указывает «DX11, 1GB VRAM, i5-750+».",
                            MinCpuModel = "Core i5-750 (4 потока) или выше",
                            MinGpuModel = "DX11, 1GB VRAM (напр. GTX 660)",
                            MinRamGB = 8,
                            Name = "Counter-Strike 2",
                            RecCpuModel = "Core i5 или лучше (6+ потоков)",
                            RecGpuModel = "DX12-class (напр. GTX 970 / RX 570)",
                            RecRamGB = 16,
                            Uuid = new Guid("33333333-3333-3333-3333-333333333002")
                        },
                        new
                        {
                            Id = 3003L,
                            Description = "Экшен-RPG от FromSoftware. Требует SSD/быструю память для стабильности.",
                            MinCpuModel = "Core i5-8400 / Ryzen 3 3300X",
                            MinGpuModel = "GTX 1060 3GB / RX 580 4GB",
                            MinRamGB = 12,
                            Name = "ELDEN RING",
                            RecCpuModel = "Core i7-8700K / Ryzen 5 3600X",
                            RecGpuModel = "GTX 1070 8GB / RX Vega 56",
                            RecRamGB = 16,
                            Uuid = new Guid("33333333-3333-3333-3333-333333333003")
                        },
                        new
                        {
                            Id = 3004L,
                            Description = "Открытый мир в школе магии. Официальные PC-спеки WB Games.",
                            MinCpuModel = "Core i5-6600 / Ryzen 5 1400",
                            MinGpuModel = "GTX 960 4GB / RX 470 4GB",
                            MinRamGB = 16,
                            Name = "Hogwarts Legacy",
                            RecCpuModel = "Core i7-8700 / Ryzen 5 3600",
                            RecGpuModel = "RTX 2060 / RX 5700 XT",
                            RecRamGB = 16,
                            Uuid = new Guid("33333333-3333-3333-3333-333333333004")
                        },
                        new
                        {
                            Id = 3005L,
                            Description = "Вестерн от Rockstar. Требования взяты из поддержки Rockstar.",
                            MinCpuModel = "Core i5-2500K / AMD FX-6300",
                            MinGpuModel = "GTX 770 2GB / Radeon R9 280 3GB",
                            MinRamGB = 8,
                            Name = "Red Dead Redemption 2",
                            RecCpuModel = "Core i7-4770K / Ryzen 5 1500X",
                            RecGpuModel = "GTX 1060 6GB / RX 480 4GB",
                            RecRamGB = 12,
                            Uuid = new Guid("33333333-3333-3333-3333-333333333005")
                        },
                        new
                        {
                            Id = 3006L,
                            Description = "Открытый мир Los Santos. Данные по обновлённой PC-версии.",
                            MinCpuModel = "Core i7-4770 / AMD FX-9590",
                            MinGpuModel = "GTX 1630 4GB / RX 6400 4GB",
                            MinRamGB = 8,
                            Name = "Grand Theft Auto V",
                            RecCpuModel = "Core i5-9600K / Ryzen 5 3600",
                            RecGpuModel = "RTX 2060 / RX 5600 XT",
                            RecRamGB = 16,
                            Uuid = new Guid("33333333-3333-3333-3333-333333333006")
                        },
                        new
                        {
                            Id = 3007L,
                            Description = "CRPG от Larian. Рекомендуемые — на оф. сайте Larian.",
                            MinCpuModel = "Core i5-4690 / Ryzen 3 1200",
                            MinGpuModel = "GTX 970 / RX 480",
                            MinRamGB = 8,
                            Name = "Baldur's Gate 3",
                            RecCpuModel = "Core i7-8700K / Ryzen 5 3600",
                            RecGpuModel = "RTX 2060 Super / RX 5700 XT",
                            RecRamGB = 16,
                            Uuid = new Guid("33333333-3333-3333-3333-333333333007")
                        },
                        new
                        {
                            Id = 3008L,
                            Description = "Королевская битва от Respawn. Мин/рек — по EA.",
                            MinCpuModel = "Core i3-6300 / AMD FX-4350",
                            MinGpuModel = "GTX 950 / Radeon HD 7790",
                            MinRamGB = 6,
                            Name = "Apex Legends",
                            RecCpuModel = "Core i5-3570K или экв.",
                            RecGpuModel = "GTX 970 / Radeon R9 290",
                            RecRamGB = 8,
                            Uuid = new Guid("33333333-3333-3333-3333-333333333008")
                        },
                        new
                        {
                            Id = 3009L,
                            Description = "Тактический шутер от Riot. Спеки по FPS-целям.",
                            MinCpuModel = "Core i3-540 / Athlon 200GE (30 FPS)",
                            MinGpuModel = "Intel HD 4000 / Radeon R5 220",
                            MinRamGB = 4,
                            Name = "VALORANT",
                            RecCpuModel = "Core i3-4150 / Ryzen 3 1200 (60 FPS)",
                            RecGpuModel = "GeForce GT 730 / Radeon R7 240",
                            RecRamGB = 4,
                            Uuid = new Guid("33333333-3333-3333-3333-333333333009")
                        },
                        new
                        {
                            Id = 3010L,
                            Description = "MOBA от Valve. Минимальные требования со Steam-страницы.",
                            MinCpuModel = "2-ядерный 2.8GHz (Intel/AMD)",
                            MinGpuModel = "GeForce 8600/9600GT или Radeon HD 2600/3600",
                            MinRamGB = 4,
                            Name = "Dota 2",
                            RecCpuModel = "4-ядерный 3.0GHz (Intel/AMD)",
                            RecGpuModel = "GeForce GTX 970 / Radeon RX 470",
                            RecRamGB = 8,
                            Uuid = new Guid("33333333-3333-3333-3333-333333333010")
                        });
                });

            modelBuilder.Entity("GameRequirements.Domain.Entites.User.DBUser", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<DateTime>("LoginDateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<Guid>("Uuid")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("GameRequirements.Domain.Entites.User.DBUserSession", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("JwtId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("Redeemed")
                        .HasColumnType("bit");

                    b.Property<string>("RefreshToken")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("RefreshTokenExpiration")
                        .HasColumnType("datetime2");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.Property<Guid>("Uuid")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Sessions");
                });

            modelBuilder.Entity("GameRequirements.Domain.Entites.Completing_computers.DBComputer", b =>
                {
                    b.HasOne("GameRequirements.Domain.Entites.Completing_computers.DBProcessor", "Processor")
                        .WithMany()
                        .HasForeignKey("ProcessorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GameRequirements.Domain.Entites.User.DBUser", "User")
                        .WithMany("Computers")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GameRequirements.Domain.Entites.Completing_computers.DBVideoCard", "VideoCard")
                        .WithMany()
                        .HasForeignKey("VideoCardId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Processor");

                    b.Navigation("User");

                    b.Navigation("VideoCard");
                });

            modelBuilder.Entity("GameRequirements.Domain.Entites.User.DBUserSession", b =>
                {
                    b.HasOne("GameRequirements.Domain.Entites.User.DBUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("GameRequirements.Domain.Entites.User.DBUser", b =>
                {
                    b.Navigation("Computers");
                });
#pragma warning restore 612, 618
        }
    }
}
